/* global monogatari */

// Define the messages used in the game.
monogatari.action ('message').messages ({
	'Help': {
		title: 'Help',
		subtitle: 'Some useful Links',
		body: `
			<p><a href='https://developers.monogatari.io/documentation/'>Documentation</a> - Everything you need to know.</p>
			<p><a href='https://monogatari.io/demo/'>Demo</a> - A simple Demo.</p>
		`
	}
});

// Define the notifications used in the game
monogatari.action ('notification').notifications ({
	'Welcome': {
		title: 'Welcome',
		body: 'This is the Monogatari VN Engine',
		icon: ''
	}
});

// Define the Particles JS Configurations used in the game
monogatari.action ('particles').particles ({

});

// Define the canvas objects used in the game
monogatari.action ('canvas').objects ({

});

// Credits of the people involved in the creation of this awesome game
monogatari.configuration ('credits', {

});


// Define the images that will be available on your game's image gallery
monogatari.assets ('gallery', {

});

// Define the music used in the game.
monogatari.assets ('music', {

});

// Define the voice files used in the game.
monogatari.assets ('voices', {

});

// Define the sounds used in the game.
monogatari.assets ('sounds', {

});

// Define the videos used in the game.
monogatari.assets ('videos', {

});

// Define the images used in the game.
monogatari.assets ('images', {

});

// Define the backgrounds for each scene.
monogatari.assets ('scenes', {
	'home': 'home.png',
	'lake': 'lake.png',
	'audience': 'audience.png',
	'vr': 'vr.png',
	'vr2': 'vr2.png',
	'planet': 'planet.png',
	'helpcentre': 'helpcentre.png'

});


// Define the Characters
monogatari.characters ({
	'Chernii': {
		name: 'Аш',
		color: '#ff00f0',
		// default_expression: 'normal',
		directory: 'Chernii',
		sprites: {
			normal: 'black_normal.png',
			angry: 'black_angry.png',
			angry2: 'black_angry2.png',
			veryangry: 'black_veryangry.png',
			disgust: 'black_disgust.png',
			fear: 'black_fear.png',
			happy: 'black_happy.png',
			happy2: 'black_happy2.png',
			sad: 'black_sad.png',
			annoyed: 'black_annoyed.png',
			confused: 'black_confused.png',
			surprised: 'black_surprised.png'
		}
	},
	'Max': {
		name: 'Максим',
		color: '#5a9de9',
		// default_expression: 'noise',
		directory: 'Max',
		sprites: {
			normal: 'max.png',
			noise: 'max_noise.png',
			fight: 'max_fight.png',
		}
	},
	'Vechna': {
		name: 'Вечна',
		color: '#3abf0a',
		directory: 'Vechna',
		// default_expression: 'normal',
		sprites: {
			normal: 'vechna_smile2.png',
			smile: 'vechna_smile.png',
			thinking: 'vechna_thinking.png',
			angry: 'vechna_angry.png',
			whitenoise: 'vechna_whitenoise.png',
		},
	},
	'Station_AI': {
		name: 'ИИ станции',
		color: '#ff0000',
		directory: 'Station AI',
		sprites: {
			normal: 'Station_AI.png',
		}
	},
	'Text': {
		name: 'Текст:',
		color: '#ffffff'
	},
	'Autor': {
		name: '',
		color: '#ffffff'	
	},
	'M': {
		name: 'M.Stork',
		color: '#5a9de9',
		// default_expression: 'noise',
		directory: 'Max',
		sprites: {
			noise: 'max_noise.png',
		},
	},

});

monogatari.script ({
	// The game starts here.
	'Start': [
			'show scene home with fadeIn', 
			'',
			'show character Chernii normal at centre with fadeIn',
			'',
			'Chernii И последний ингредиент - как ты любишь, светлячки!',
			'Аш поставил на стол тарелку с салатом и повернул голову в сторону сестры, лежащей на полу.',
			'Он задавался вопросом, спит она или нет.',
			'Chernii Конечно, Вечна, ты в сети. Спишь на кровати, работаешь на полу.',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Всмотрелся в лицо девушки, но вместо него увидел белый шум.',
			'Vechna ...',
			'hide character Vechna',
			'show character Chernii annoyed at centre with fadeIn',
			'Chernii Чертова Луна! Сухая лаборатория, в которой ты или обрабатываешь данные в сети...',
			'Chernii ...или убиваешь время, чтоб не сойти с ума.',
			'show character Chernii normal at centre',
			'По старой привычке он подошел к кровати сестры, чтобы поправить.',
			'Вот только она была нетронута...',
			'show character Chernii annoyed at centre',
			'Chernii Ты опять 20 час работаешь?!',
			'Chernii Что бы ты не делала в сети - это важнее, чем я, впрочем, как и всегда.',
			'Chernii Чувствую себя в какой-то антиутопии.',
			'show character Chernii normal at centre',
			'Chernii Живем в одной комнате, но не можем даже поговорить.',
			'Chernii Если бы аризонский эксперимент Биосфера 2, с живущими в изолированных куполах людьми, был в наше время...',
			'Chernii ...разделившись на 2 группы, испытуемые бы точно забанили друг друга.',
			'Chernii Дальний космос подводят не технологии, а наша психика.',
			'Chernii Но я на тебя не злюсь, уже не злюсь.',
			'Chernii Это отчаяние, от того что ты от меня стала дальше, чем любая планета за пределами Луны. Правда же?',
			'Он снова посмотрел на сестру.',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Vechna ...',
			'hide character Vechna',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Но чем черт не шутит?',
			'Он лег на свою кровать и зашел в сеть.',
			'Text "Пользователь Вечна Хом недоступен."',
			'jump Scene1'
		],
	'Scene1': [
		'show scene home with fadeIn',
		'70 земных дней назад.',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Классно, что в фудрариум ты поселил светлячков! Сверчки уже надоели.',
		'Vechna Правда, еда слишком свежая.',
		'Из тарелки девушки медленно выполз чудом выживший светлячок.',
		'show character Vechna thinking at centre',
		'Vechna Ну рили?! Я не могу это есть! Их нужно оставлять без кислорода хотя бы на десять минут!',
		'Vechna Сверчки живы, а ужин убит.',
		'hide character Vechna',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii Я как могу освобождаю тебе время для работы, зная как ты ее любишь.',
		'show character Chernii normal at centre',
		'Chernii Точно больше, чем жизнь в реальности.',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Нужно сходить в кино! А может, запустим змея?',
		'show character Vechna smile at centre',
		'Vechna Хотя, мы ведь в лавовых туннелях под поверхностью Луны. Упс!',
		'hide character Vechna',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii Я не о том, просто я чем могу, тем тебе и помогаю. Ты совсем не понимаешь мои мотивы?',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Понимаю. Даже лучше, чем ты.',
		'Vechna Знаешь, как мне сложно конкурировать за работу с сетевиками?',
		'Vechna Они скопировались в сеть, им ни есть, ни спать не надо.',
		'Vechna Прислал ровер данные от Альфа Центавра, ты их сразу взял!',
		'Vechna И - хопа! Запустил обработку в параллельном потоке.',
		'Vechna А я, простая смертная: одно доделай, ресурсы освободи… Тогда как сетевики уже статьи публикуют!',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii И? Закончишь мысль?',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Я бы строила симуляции далеких планет и галактик одна из первых, если б присоединилась к их “фандому”.',
		'Vechna Но ты же не пустишь, ты лучше освободишь мне дополнительный часик.',
		'Она играла с вяло ползающим по столу светлячком. Он все еще отливал холодным синим светом.',
		'show character Vechna normal at centre',
		'Vechna Аш, почему ты так против, если понимаешь…',
		'Она сказала это с насмешкой.',
		'Vechna …как сильно я люблю визуализировать далекие миры по набору нулей и единичек?',
		'Vechna Оригинал жил бы с тобой, не тужил и не возмущался.',
		'hide character Vechna',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii Даже не доказано, идентичная личность выходит после копирования, или нет.',
		'show character Chernii normal at centre',
		'Chernii Это как биохакеры в 21 веке – вроде продлевают жизнь, а вроде, наоборот. Недостаточно данных!',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Но...',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Тебе придется делить свою славу и все остальное со второй “я”. Думаю, вы не поладите. И кто-то кого-то обязательно удалит.',
		'Chernii Я просто боюсь за тебя. Ты слишком увлечена открытиями.',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Сам пилишь импланты, выражающие эмоции - как универсальный визуальный язык для разных культурных кодов.',
		'show character Vechna angry at centre',
		'А горю открытиями здесь я?',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Я совмещаю жизнь здесь и работу над проектом. И, вдобавок, еще и помощь тебе.',
		'Chernii При интенсивной загрузке, я бы научил искусственный интеллект Ушей зайца распознавать базовые эмоции месяца за 3! Часть эмоций уже работает.',
		'hide character Chernii',
		'show character Vechna smile at centre with fadeIn',
		'Vechna Типа как когда ты бесишься? Можно сказать я тебе уже помогаю обучать ИИ ушей.',
		'hide character Vechna',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii Ага, пропадая по 20 часов в сети!',
		'hide character Chernii',
		'show character Vechna angry at centre with fadeIn',
		'Vechna Ах, вот оно как! Ну тогда, дорогой брат, я помогу, чем могу.',
		'Vechna Нифига мы с тобой не Диппер и Мейбл! Иди работай!',
		'show character Vechna whitenoise at centre with fadeIn',
		'Лицо девушки расплылось, и вместо зеленых глаз сестры, Аш увидел белую рябь.',
		'Не успел он возмутиться, как она уже распространилась на все ее тело.',
		'hide character Vechna',
		'show character Chernii angry at centre with fadeIn',
		'Chernii Ты улыбаешься?',
		'hide character Chernii',
		'show character Vechna whitenoise at centre with fadeIn',
		'Девушка собрала оставшихся в живых, и, уже было собравшихся расползтись из тарелки светлячков, и убрала их в фудрариум, к остальным насекомым.',
		'jump Scene2'
		],
		'Scene2': [
			'show scene home with fadeIn',
			'На следующий день после блока.',
			'show character Vechna whitenoise at centre with fadeIn',
			'Vechna ...',
			'hide character Vechna',
			'show character Chernii angry at centre with fadeIn',
			'Парень пытался докричаться со сестры.',
			'Chernii Сразу видно рациональное мышление!',
			'show character Chernii normal at centre',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Vechna ...',
			'hide character Vechna',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Хорошо, проведем другой эксперимент. На чем там раньше писали?',
			'Он оглянулся по сторонам. Девушка подошла к кухонной стойке.',
			'Chernii Есть мысль!',
			'Он встал рядом с ней и достал самую большую тарелку, открыл фудрариум с растениями и вырвал пучок петрушки.',
			'Оборвал со стеблей листья, выложил на тарелке текст.',
			'Text Поговори!',
			'Поставил тарелку под нос девушке, уже сидящей за столом.',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Vechna ...',
			'hide character Vechna',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Ты упрямая или заблокировала все способы передачи информации? Звуки, буквы, цифры и рисунки?',
			'Chernii Не верю.',
			'У стойки он начистил еще стеблей петрушки и выложил на тарелке новый текст, который поставил на стол перед девушкой.',
			'“Копируйся в сеть”',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Vechna ...',
			'hide character Vechna',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Ты все-таки это сделала…',
			'show character Chernii annoyed at centre',
			'Chernii Отличный способ решать вопросы! Кто тут из нас еще старший!',
			'show character Chernii normal at centre',
			'Его голову посетила пугающая мысль: вдруг она вместо него тоже видит белый шум?',
			'Chernii И что мне делать? Обездвижить тебя, пока не разблокируешь каналы связи?',
			'Chernii Проверим, видишь ли ты меня.',
			'Оглядываясь по сторонам, его взгляд упал на кухню. Особо там больше не на что и смотреть.',
			'Пооткрывав шкафы, он достал нож. Сел на кровать и положил руку ладонью вверх на колено.',
			'Chernii Кровь на полу ты увидишь, даже если я заблочен, но на моей одежде - нет.',
			'Полоснул руку ножом.',
			'Chernii * Мысли * А в виаре с ощущениями на максимуме - больней!',
			'Он ждал, кровь впитывалась в ткань, ее тепло уже чувствовалось в районе икры, обещая скоро растечься по полу.',
			'Силуэт, залитый белым шумом, отложил в сторону палочки для еды и направился в сторону кухонных шкафов.',
			'Chernii Ты заметила? Или не наелась?',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Девушка достала тюбик из верхнего шкафчика и положила его на кровать рядом с братом.',
			'hide character Vechna',
			'show character Chernii normal at centre with fadeIn',
			'Он прочел: клей для обработки порезов.',
			'Chernii Я был прав! Ты меня видишь!',
			'И грустно закончил.',
			'Chernii Только лишь видишь...',
			'Он подошел к источнику с водой и смыл кровь. Обсушил теплым воздухом, затем  нанес клей.',
			'Chernii Значит, придется тестировать импланты в боевых условиях. И нужно научить ИИ узнавать эмоции, чтобы они отображались на заячьих Ушах.',
			'Chernii Я очень хочу показать тебе свои чувства. И они не делают меня счастливым.',
			'Chernii Вот и повод вернуться в любимую игру.',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Вечна начала растяжку, используя минимальные, необходимые упражнения, чтобы скорее вернуться в мир сети.',
			'hide character Vechna',
			'show character Chernii annoyed at centre with fadeIn',
			'Chernii Не смогу не тебя смотреть после сложной игры. Мне ведь нужно море, целый океан крови и страданий.',
			'jump Scene3'
		],
		'Scene3': [
			'show scene audience with fadeIn',
			'',
			'show character Chernii normal at centre with fadeIn',
			'Прошло 70 дней после блокировки Вечны.',
			'Если люди на Лунной Станции куда-то и выходили - это были прогулки под Куполом с произрастающей зеленью и спортзалы.',
			'Лекционный зал никто не использовал.',
			'Для чего идти куда-то, если любое выступление транслируется в сеть?',
			'Теперь аудитория походила на место, куда можно сбежать.',
			'Иногда сюда заглядывали мобильные камеры, которые следят за порядком, или роботы уборщики, убирающие просочившуюся с поверхности пыль.',
			'Аш натянул на ладонь рукав толстовки и провел по лавке, проверив, что на той не осела мелкая фракция.',
			'Лунная пыль мелкая, как порошок, и острая, как стекло.',
			'Ведь на спутнике Земли нет ветра и воды, которые закругляют ее края.',
			'Chernii Отлично, сегодня ничего не попадет в мои легкие. Ещё рака мне не хватало.',
			'Он лег на скамейку.',
			'В последнюю секунду ему показалось, что открылась дверь в аудиторию, но он уже был в другой реальности.',
			'jump Scene4'
		],
		'Scene4': [
			'show scene vr with fadeIn',
			'',
			'show character Chernii normal at centre with fadeIn',
			'Вокруг гудели звуки. Аш выкрутил их на минимум и отправился к двери с надписью "Game".',
			'Она должна была привести его в ту игру, в которую он играл последний раз.',
			'С тех пор, как он узнал, что Вечна его видит, Аш пропадал в хорроре.',
			'Раз за разом он пытался поставить себя в самые стрессовые ситуации.',
			'Чем чаще парень испытывал эмоцию, тем с большей вероятностью она отображалась на дисплеях его имплантов.',
			'Аш всегда выбирал роль жертвы.',
			'В отличии от остальных, ему было не так уж интересно проектировать испытания, как показывать другим свое превосходство.',
			'Chernii Люблю выигрывать на чужом поле боя.',
			'Chernii И сегодня мне нужен самый изощренный проектировщик игр.',
			'Он выбрал верхнее имя в рейтинге создателей хорроров и отправил приглашение.',
			'Подтверждение пришло сразу.',
			'Chernii Надеюсь, ты дашь мне море негативных впечатлений. Что-то пооригинальней зомби.',
			'Молодой человек с кибер-ушами вошел в дверь.',
			'jump Scene5'
		],
		'Scene5': [
			'show scene vr2 with fadeIn',
			'',
			'show character Chernii normal at centre with fadeIn',
			'Аш привычно выкрутил на максимум остроту чувств.',
			'В любой стимуляции, чтобы не травмировать человека, как психически, так и физически - в виаре ты волен притупить ощущения.',
			'Игровая площадка выглядела невинно. Немного и довольно смутно напоминая старый добрый “майнкрафт”.',
			'Только в этой игре правила нужно изучить на собственной шкуре.',
			'show character Chernii confused at centre',
			'Chernii Эм, и у этого проектировщика самый высокий рейтинг? И какой алгоритм его составляет?',
			'Блоки на локации вели в разных направлениях. Перед героем предстало пустое пространство, освещенное огнями.',
			'Chernii И какая цель игры?',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Ищи блок, где сможешь удовлетворить самую базовую потребность.',
			'hide character M',
			'show character Chernii annoyed at centre with fadeIn',
			'Chernii Много ты знаешь о моих потребностях.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Есть то, чего бояться все. Удачи!',
			'hide character M',
			'show character Chernii normal at centre with fadeIn',
			'Проектировщик отключился. Аш стоял в задумчивости, размышляя, чего же ему ждать от “топовой” игры.',
			'Нет ни оружия, ни пугающей атмосферы.',
			'Chernii Найти блок? Скучно, сил нет. Самый высокий рейтинг, черт возьми...',
			'Он пошел по блокам. После первого шага что-то как будто бы изменилось.',
			'Аш зевнул. А потом еще. И еще.',
			'Не обращая на это внимания, парень продолжал двигаться.',
			'Царящая вокруг тишина способствовала нарастающему раздражению, и как будто бы усиливала появившуюся головную боль.',
			'Он заглядывал за блоки, стучал по ним и прыгал, пытаясь понять: чего же от него хотят?',
			'Голова уже начала раскалываться на части. Теперь и воздух становился тяжелым.',
			'Поднявшись на небольшую ступеньку, Аш попытался сделать глубокий вдох. Он задыхался.',
			'Chernii Головная боль, сонливость и удушье. Нехватка кислорода?',
			'Chernii Экзогенная гипоксия – пооригинальней зомби. Уже интересней.',
			'Chernii Кислород действительно базовая потребность.',
			'Он сел на пол.',
			'Chernii Очень злая шутка для жителей Луны, погибающих от разгерметизации станций.',
			'Головная боль стала невыносимой и мешала сосредоточиться на задании.',
			'Впервые он пожалел, что использовал всю остроту чувств, а не притупил их.',
			'Можно смириться с раной в ноге или укусом какой-то твари: как-то раз ему откусили голову, напоминало сильный ожог.',
			'Chernii Непривычно. Значит, нужен блок?',
			'Chernii Так, я был здесь? Вот и дезориентация со снижением когнитивных способностей.',
			'Сердце бешено колотилось от каждого шага, а идти становилось все труднее.',
			'Chernii В конце я должен потерять сознание.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Не потеряешь. Это же игра.',
			'hide character M',
			'show character Chernii normal at centre with fadeIn',
			'',
			'Шел второй час, Ашу казалось, что он находится на грани состояния, когда вот-вот, через секунду, упадет.',
			'Перед глазами было мутно, словно в густом смоге.',
			'Тело отказывалось слушаться. Парень готов был поклясться, что не раз обошел все игровое пространство.',
			'show character Chernii angry at centre',
			'Chernii Неужели нужно лезть на верхние блоки?',
			'Он перешел на шепот.',
			'show character Chernii annoyed at centre',
			'Chernii Верните кислород!',
			'Он ухватился руками за край и попробовал подтянуться.',
			'Chernii Смешно. Не могу даже нормально видеть, какое лезть... Это кошмар.',
			'Chernii Я хочу закончить игру.',
			'Никто не отвечал.',
			'Chernii ...',
			'show character Chernii normal at centre',
			'Он хотел убедить проектировщика, но понял, что уже не способен даже говорить. Только думать:',
			'Chernii * Мысли * Как долго я могу здесь проваляться?',
			'Chernii * Мысли * В сознании, с жжением во всем теле...',
			'Он пытался продолжить внутренний диалог, но теперь не мог даже думать.',
			'Его охватил страх. Самый жуткий и первобытный – нехватка кислорода.',
			'Игрок не мог ползти по ступеням вниз, поэтому скатился.',
			'Парень приближался к границе блоков, где начиналась черная, непроглядная тьма.',
			'Он очень хотел проиграть. Только как это сделать?',
			'Прежде, чем сброситься во тьму, он почувствовал ужас, живот скрутило.',
			'Chernii * Мысли * А что, если игра не закончится?',
			'Упав вниз, он не сможет вернуться и никогда не доберется до блоков.',
			'show character Chernii fear at centre with fadeIn',
			'Перед глазами высветилось уведомление:',
			'Изучена новая эмоция - страх.',
			'Он перевалился за край, ожидая ощутить падение, но почувствовал холодную поверхность и удар головой.',
			'show character Chernii normal at centre',
			'Вдох вызвал жгучую боль.',
			'Значит, страх.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Невидимый, зато огромный блок открыт! Довольно хитро, а?',
			'M Ты почти 2 часа бродил, обычно сбрасываются после часа тяжелой гипоксии.',
			'hide character M',
			'show character Chernii angry at centre with fadeIn',
			'Chernii Ты садист!',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Это хоррор, ты вообще дольше меня играешь. И только за жертву. К кому еще вопросы?',
			'M Месье мазохист, к вашим услугам садист!',
			'Он произнес это со смехом, пока Аш пытался прийти в себя.',
			'hide character M',
			'show character Chernii annoyed at centre with fadeIn',
			'show character Chernii normal at centre',
			'Chernii Это для науки.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Вся наука для человеческого эго, не заливай.',
			'M Не обижайся. Хочешь кастомную игру?',
			'hide character M',
			'show character Chernii angry at centre with fadeIn',
			'Chernii ...',
			'hide character Chernii',
			'Аш вышел из игры.',
			'show character M noise at centre with fadeIn',
			'M Постоянно они обижаются…',
			'jump Scene6'
		],
		'Scene6': [
			'show scene vr with fadeIn',
			'show character Chernii normal at centre with fadeIn',
			'Chernii До сих пор трясет, но эффективно - ничего не скажешь.',
			'Chernii Пара часов, и код ушей смог узнать в мозгу страх, а потом отобразить на дисплее.',
			'Chernii Хотя страх я до этого часто чувствовал, скорее всего, там получил недостающие данные.',
			'Его внимание привлекло уведомление, появившееся перед лицом.',
			'"Сообщение демонстрируется принудительно, поскольку до этого было проигнорировано 10 уведомлений в 3 каналах связи."',
			'show character Chernii fear at centre',
			'Chernii * Мысли * Похоже, это проблемы.',
			'Сообщение: Вам нужно явиться в Центр Помощи.',
			'show character Chernii normal at centre',
			'Chernii Конечно, я приду.',
			'Он усмехнулся и вышел из сети.',
			'Chernii * Мысли * Конечно, я не приду! Мне нужно домой.',
			'jump Scene7'
		],
		'Scene7': [
			'show scene audience with fadeIn',
			'Аш Он лежал на лавке и ждал, пока скелетные мышцы начнут его слушаться.',
			'Состояние напоминало сонный паралич.',
			'Чип в голове позволял не только выходить в сеть, собирать данные о здоровье и эмоциях человека.',
			'Но и синтезировать нейропередатчики для блокировки движений, как во время сна.',
			'В конце зала раздался звук, словно что-то поставили на лавку.',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Кто здесь?',
			'Контроль над телом вернулся. Он сел и увидел перед собой мобильную камеру.',
			'show character Chernii fear at centre',
			'Chernii Я уже и забыл.',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Пройдите в Центр Помощи. Это не займет много времени. Спасибо.',
			'hide character Station_AI',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Пожалуйста...',
			'jump Scene8'
		],
		'Scene8': [
			'show scene helpcentre with fadeIn',
			'',
			'show character Chernii normal at centre with fadeIn',
			'Аш встал с кушетки.',
			'Chernii Все впорядке?',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Уровень кортизола, пролактина, тиреотропного гормона и магния показал…',
			'Station_AI ...что вы испытываете стресс, несовместимый с приемлемыми когнитивными способностями на протяжении 2 месяцев.',
			'hide character Station_AI',
			'show character Chernii confused at centre with fadeIn',
			'Chernii И для чего я здесь? Чип и так в реальном времени присылает вам показатели.',
			'show character Chernii normal at centre',
			'Chernii Зря столько датчиков в тело помещали?',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Правила требуют перепроверки данных.',
			'Station_AI Ваше состояние оценивается как опасное для окружающих, находящихся в замкнутой системе жизнеобеспечения.',
			'Station_AI Необходимо восстановить показатели до уровня, который считается здоровым.',
			'hide character Station_AI',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Как это выглядит?',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Первая ступень восстановления – когнитивная терапия: вы должны посещать свидания.',
			'Station_AI Знакомы с системой свиданий?',
			'hide character Station_AI',
			'show character Chernii normal at centre with fadeIn',
			'Chernii * Мысли * А ты не знаешь? Мы же заучивали правила перед отправкой.',
			'Chernii К сожалению, не помню.',
			'Chernii * Мысли * И как мне отвертеться? Не мое это...',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Все эксперименты по длительному пребыванию человека в замкнутом пространстве указывали, что один из самых высоких факторов риска для провала миссии – человеческая психика.',
			'Station_AI Например, участники эксперимента Биосфера 2 разделились на две группы и снизили эффективность работы.',
			'Station_AI Член 3 экипажа Станции Клоун нарушил герметичность, что привело к жертвам и дорогостоящему ремонту станции.',
			'hide character Station_AI',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Наверное, их проблема была в том, что они слишком много общались. Я со своей "причиной стресса" даже не разговариваю.',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Это хорошо.',
			'hide character Station_AI',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Наоборот.',
			'Аш усмехнулся.',
			'Chernii * Мысли * Стресс отслеживать научились, а вот с определением источника проблема.',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Человек может непредсказуемо повести себя в замкнутом пространстве.',
			'Station_AI Поэтому, необходимо общаться с людьми извне. Вы обязаны ежедневно посещать свидания в сети.',
			'hide character Station_AI',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Вся моя семья здесь. Я готов пойти на встречу в сети, но с человеком со станции.',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Свидания могут быть организованы только с жителями Земли.',
			'Station_AI Коммуникация с экипажем незначительно снижает риски психических расстройств.',
			'hide character Station_AI',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Значит нет?',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Вы не можете организовать свидание с жителем станции.',
			'Station_AI Вам будет выслан план лечения. Убедительная просьба следовать ему.',
			'hide character Station_AI',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Могу отказаться?',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Если в течении 2 недель вы не покажете положительный прогресс, вас изолируют от остальных.',
			'Station_AI Вы получите принудительную визуальную и звуковую блокировку – белый шум',
			'Station_AI Вы знаете что это? Если в сети вы можете поставить блок внешности, здесь вы будете заблокированы в реальности.',
			'hide character Station_AI',
			'show character Chernii fear at centre with fadeIn',
			'Chernii Сталкивался с этим разок.',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI При попытке тактильного контакта – вам будет отказано в возвращении на Землю.',
			'hide character Station_AI',
			'show character Chernii normal at centre with fadeIn',
			'Chernii * Мысли * Значит, Вечна меня не увидит...',
			'Chernii Что тут сказать, я согласен...',
			'jump Scene9'
		],
		'Scene9': [
			'show scene home with fadeIn',
			'show character Chernii normal at centre with fadeIn',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Силуэт, залитый белым шумом, встал в мостик из положения стоя, а затем на руки.',
			'hide character Vechna',
			'show character Chernii fear at centre with fadeIn',
			'Chernii Сейчас ты меня хотя бы видишь, а что будет через 2 недели?',
			'Chernii Интересно, как это, когда ты для всех заблочен. Хотя, совсем не интересно…',
			'show character Chernii normal at centre',
			'Аш знал, что она его не слышит – но с другими, особенно с незнакомцами с Земли, говорить не хотелось.',
			'Chernii Ирония - я считаюсь опасным элементом за то, что сам себя подвергаю стрессу.',
			'Chernii Потому что ИИ станции неверно определил мою настоящую проблему.',
			'show character Chernii annoyed at centre',
			'Chernii Разреши правила станции приглашать на свидания жителей Луны – это бы все решило.',
			'Chernii Ирония – можно встретиться в сети с жителями Земли, но не с человеком в твоей комнате.',
			'show character Chernii normal at centre',
			'Chernii Расстояние приняло странную форму.',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Девушка села на продольный шпагат.', 
			'hide character Vechna',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Придется финализировать эксперимент с имплантами.',
			'Chernii Терапия ИИ станции для меня бесполезна, а других идей нет.',
			'Chernii А если повезет наладить с тобой контакт - проблема решится сама собой.',
			'Ему пришло уведомление с заголовком "План терапии".',
			'Chernii Не поверите, но мне нужно поиграть.',
			'Chernii Теперь мой личный доктор – психопат, проектирующий ужасы.',
			'jump Scene10'
		],
		'Scene10': [
			'show scene audience with fadeIn',
			'На следующий день',
			'show character Chernii normal at centre with fadeIn',
			'Войдя в аудиторию, парень прислушался. В прошлый раз казалось, что здесь кто-то есть.',
			'В темном углу аудитории раздался шорох.',
			'Chernii Привет?',
			'Ему никто не ответил.',
			'show character Chernii confused at centre',
			'Chernii Роботы?',
			'show character Chernii normal at centre',
			'Он по привычке провел рукавом по поверхности скамейки, проверяя ее на наличие пыли.',
			'В неиспользуемых помещениях экономят на уборке и питании вентиляции, а лунная пыль всегда найдет, куда просочиться.',
			'Аш лег и закрыл глаза. Тело расслабилось. Он вошел в сеть.',
			'jump Scene11'
		],
		'Scene11': [
			'show scene vr with fadeIn',
			'',
			'show character Chernii normal at centre with fadeIn',
			'Вокруг было шумно. Сегодня Аш не стал убавлять этот звук. Гул, казалось бы, заглушал его волнение.',
			'Аш постоял у входа, собираясь с мыслями.',
			'show character Chernii fear at centre',
			'Chernii Стоит ли играть с тем парнем?',
			'show character Chernii normal at centre',
			'Он посмеялся над собой.',
			'show character Chernii fear at centre',
			'Chernii Через пару недель я, возможно, не поиграю ни с кем. Зачем мелочиться?',
			'В прошлый раз он не запомнил ник проектировщика. Но, знал, где искать.',
			'show character Chernii normal at centre',
			'Chernii Заслуженное первое место в рейтинге.',
			'Chernii Надеюсь, сегодня будет не лучшая твоя работа.',
			'jump Scene12'
		],
		'Scene12': [
			'show scene vr2 with fadeIn',
			'',
			'show character Chernii normal at centre with fadeIn',
			'Аш видел ту же локацию, что и в прошлый раз. Он вспомнил весь спектр боли и страха, что пережил на ней.',
			'show character Chernii fear at centre',
			'Chernii Одни воспоминания вызывают отвратительные чувства.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Хороший проектировщик помнит про предыдущий опыт и использует его.',
			'M Быстро ты вернулся. Наука не ждет, а?',
			'hide character M',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Давай начинать игру. Какие вводные?',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Цель игры, которая позволит выйти до того, как таймер дойдет до нуля, откроется в процессе.',
			'hide character M',
			'show character Chernii surprised at centre with fadeIn',
			'Chernii Таймер?',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Да, игра ограничена по времени. Но я уверен, ты отгадаешь загадку и выйдешь быстрее.',
			'Перед Ашем появился таймер 12:00, он начал отсчет назад.',
			'hide character M',
			'show character Chernii annoyed at centre with fadeIn',
			'Chernii 12 часов? Не уважаешь ты чужое время.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M С тобой потому и интересно играть: ты не ставишь проектировщику ограничений по контролю.',
			'M И острота чувств выкручена на полную. Красота!',
			'hide character M',
			'show character Chernii confused at centre with fadeIn',
			'Chernii Жалею об этом.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Таймер давно идет. Не люблю нарушать свои правила. Удачи!',
			'hide character M',
			'show character Chernii normal at centre with fadeIn',
			'Chernii В другой раз у тебя не будет такой творческой свободы.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M ППосле сегодняшнего - точно!',
			'hide character M',
			'show character Chernii confused at centre with fadeIn',
			'Chernii Зря, очень зря я не ограничил время игры.',
			'show character Chernii normal at centre',
			'Он вздохнул.',
			'Chernii И где изменения? Что тут делать? Чем управлять или что искать?',
			'Он почувствовал покалывание в ногах, хотел было отпрыгнуть - но понял, что не может.',
			'Сегодня создатель локации играл не только с пространством, но и с его телом.',
			'show character Chernii annoyed at centre',
			'Chernii Чтоб я хоть раз еще открыл полный доступ проектировщику!',
			'show character Chernii normal at centre',
			'Ноги сами вели его влево, по ступеням, с которых он катился в прошлый раз, не в силах идти самостоятельно от нехватки кислорода.',
			'Поднявшись на платформу, он увидел в углу зайцев. Животные столпились у одного блока. Было непонятно, чем они заняты.',
			'show character Chernii surprised at centre',
			'Chernii Розовые, синие, зеленые - и все лысые!',
			'Сквозь прозрачную кожу зайцев виднелась их кровеносная система, раскрашенная в яркие, неоновые цвета.',
			'Chernii Как ни странно, это даже красиво, а не противно.',
			'show character Chernii confused at centre',
			'Chernii * Мысли * А совпадение ли то, что мой личный “доктор” выбрал именно зайцев?',
			'show character Chernii normal at centre',
			'Chernii * Мысли * Пожалуй, в сети мне стоит использовать белый шум.',
			'Chernii * Мысли * Было слишком просто узнать, кто мне нравится.',
			'Рядом с собой он заметил графин с узким горлышком.',
			'Chernii Уже что-то.',
			'Chernii А вы что там делаете?',
			'Он пытался с расстояния рассмотреть, чем занимаются зайцы, повернувшись мордочками к блоку.',
			'Он же мог дотянуться только до графина, но не сдвинуться с места, куда его привели ноги.',
			'Аш вытер пот с лица.',
			'Chernii Здесь становится жарко. Похоже, я понял задумку.',
			'Один из зайцев немного отодвинулся в сторону, и парень понял, что животные слизывают влагу с поверхности стены.',
			'Температура росла, сухой воздух начинал обжигать кожу.',
			'Парень еще раз попытался подойти к тени - те перемещались, но не оказывались там, где стоял он.',
			'Ноги не двигались. Он мог удержать равновесие, но не покинуть свое место.',
			'show character Chernii surprised at centre',
			'Chernii Это будут веселые почти двенадцать часов...',
			'Он потянул руку к графину, чтоб выпить часть, но тут заметил, как с поверхности блока облаком испаряется жидкость.',
			'show character Chernii normal at centre',
			'Зайцы разбежались, занимая место в тени.',
			'show character Chernii angry2 at centre',
			'Chernii Да ты издеваешься! Я должен выбрать, кому дать воду?',
			'Chernii Проблема вагонетки давно не в моде.',
			'show character Chernii normal at centre',
			'Chernii * Мысли * Я не протяну одиннадцать часов, или точно попаду в Центр Помощи. С настоящим расстройством психики.',
			'Он потряс графин в руке.',
			'Chernii Из такого горлышка зайцы не могут пить. Лить на пол, чтобы слизывали?',
			'Chernii Как-то просто.',
			'Парень чувствовал, как влага испаряется с кожи. Его посетила мысль, что пройдет немного времени, и она треснет.',
			'Таймер показывал 11:12',
			'Chernii Не прошло даже часа! Слишком хочется пить. Так ли нужна зайцам вода?',
			'Chernii Они могут спрятаться в тени. Я - нет.',
			'Chernii Как выйти из игры раньше?',
			'show character Chernii fear at centre',
			'Он старался быстрее придумать план, вспоминая, как в прошлый раз потерял способность формулировать мысли.',
			'Chernii А там я провел только 2 часа… Страшно представить, что произойдет здесь.',
			'Невыносимый жар плавил его. И к физическим страданиям на совесть приросли этические.',
			'Chernii Вылить на пол? Или выпить самому? Проведем эксперимент. Вся жизнь сплошной эксперимент.',
			'Он сделал глоток, плеснул немного воды под ноги. Зайцы ринулись к нему.',
			'Chernii Иди ко мне!',
			'Он поставил графин рядом, немного опасаясь, что от горячего пола вода будет быстрее испаряться.',
			'И взял на руки зайца с ярко-зеленой кровеносной системой. Тот был недоволен, что упускает возможность попить из свежей лужицы.',
			'Chernii У меня сестренка любит такой цвет.',
			'Зайчик был прохладный и гладкий, а на брюшке виднелась надпись - Тархун.',
			'show character Chernii angry at centre',
			'Аш с ужасом отбросил зайца, тот упал и, пища, убежал в дальнюю тень. Остальные, испугавшись, разбежались в стороны.',
			'Chernii Парень, ты не садист, а психопат! Мне правда нужны нормальные знакомые.',
			'Chernii Значит, вода - приманка?',
			'Он скривил рот, от чего губа треснула и во рту появился привкус крови, напоминающий железо.',
			'show character Chernii fear at centre',
			'Он был готов поспорить, что не потеряет сознание и не умрет, пока не выйдет время. Он не знал, как продержится 10 часов 45 минут.',
			'Chernii Я не могу их пить! И жалко, и мерзко.',
			'show character Chernii normal at centre',
			'Спустя 2 часа началась аритмия. Голову словно сверлили.',
			'Игрок пытался спать. Открывать глаза стало больно, словно в них насыпали горячий песок.',
			'Но он все равно, время от времени поднимал взгляд к таймеру и пил воду.',
			'Подняв голову в этот раз, Аш забыл про боль. Забыл про все.',
			'show character Chernii surprised at centre',
			'Chernii 24 часа? Было же меньше 8!',
			'Chernii * Мысли * У меня бан скоро, 24 часа – слишком! Слишком!',
			'show character Chernii normal at centre',
			'Chernii Ладно, зайцы не настоящие, и пожалуй, пока я могу соображать, придется выигрывать эту больную игру.',
			'Зайцы сидели в нескольких метрах от него, прячась в блаженной тени.',
			'Он плеснул немного жидкости на колонну рядом.',
			'Стоя несколько часов, игрок разгадал смысл движущихся теней - зайцы не могут долго находиться в одном месте.',
			'Chernii Это не настоящие зайцы. Но, все равно - жалко!',	
			'Один из них, с розовыми венками, запрыгал к влажной колонне.',
			'show character Chernii confused at centre',
			'Chernii Интересно, какой у тебя вкус? Ну и мысли.',
			'show character Chernii normal at centre',
			'Поймать розового зайца было просто. Прохладное животное спокойно сидело на руках, ожидая пока его отпустят попить. Остальные звери внимательно наблюдали.',
			'Chernii Хоть бы сопротивлялся! Как тебя пить?!',
			'Его колотило от отвращения. Или от обезвоживания, определить уже было сложно, да и нужно ли?',
			'Он хотел вгрызться в самую толстую вену, но услышал дыхание зайца. Живое.',
			'Тогда руки сами свернули шею животному.',
			'Chernii Не мучать же живого. Не настоящего, не живого...',
			'Он надкусил вену и стал пить лимонад. Держа зайца выше головы.',
			'show character Chernii annoyed at centre',
			'Chernii * Мысли * Никогда больше не смогу пить бабл гам. Зачем лимонад, а не вода?',
			'show character Chernii normal at centre',
			'По глазам зайцев он понимал, что теперь те станут осторожней.',
			'Через 20 минут он понял, почему в зайцах был лимонад - он утолял жажду совсем ненадолго и она появлялась с новой силой.',
			'Chernii Мог бы сделать в них больше жидкости.',
			'Chernii Попробую обойтись одним.',
			'Ему было противно и от того, кто это придумал, и от себя самого.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Поздравляю, ты нашел способ выйти быстрее.',
			'hide character M',
			'show character Chernii annoyed at centre with fadeIn',
			'Chernii Ты точно с отклонениями от нормы. Я поймаю всех ненастоящих зайцев, но пить их не стану.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M А что, не вкусно?',
			'hide character M',
			'show character Chernii angry at centre with fadeIn',
			'Chernii Лучше тебе не попадаться мне на глаза! Серьезно, у меня мало времени, но на тебя я его найду!',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Зато здесь у тебя куча времени!',
			'hide character M',
			'show character Chernii normal at centre with fadeIn',
			'Жара усилилась. Тени двигались, а зайцы следовали за ними.',
			'Chernii Ладно. Количество теней уменьшается. Это упрощает и ускоряет мою игру.',
			'Но вскоре он открыл вторую сторону медали.',
			'С одной стороны, у зайцев не было большого выбора, куда бежать, а с другой стороны, если они оказывались рядом - он не мог медлить.',
			'Когда добыча близко - нужно ловить. Он лил воду на стену колонны и ждал.',
			'Chernii Вы напоминаете антилоп, которых на водопое ждет крокодил. Они знают об этом, но измученные жаждой вынуждены рисковать. Но вы не настоящие зайцы.',
			'Игроку удавалось поймать в среднем одного зверька в час, но теперь они не вели себя так уж мирно.',
			'И самое жуткое и мерзкое чувство у него просыпалось от того, что зайцы смотрели, как он убивает их сородича.',
			'show character Chernii fear at centre',
			'Chernii Не настоящие зайцы.',
			'Повторял он себе вновь и вновь.',
			'А Вечна настоящая, мне очень нужно домой!',
			'show character Chernii normal at centre',
			'Теней почти не осталось, зайцы сбивались в маленькие стаи. На таймере высветилось 20:00 часов',
			'Последний заяц, которого парень пытался поймать, свернул графин.',
			'И зайцы ринулись к луже, надеясь, что в толпе поймают не их.',
			'show character Chernii fear at centre',
			'У Аша родилась дикая идея.',
			'Он стал хватать животных и сворачивать им шеи. Пятерым удалось вырваться, четверо остались с ним, уже бездыханными.',
			'Перед ним появился текст - чтобы закончить игру, поймайте всех зайцев.',
			'show character Chernii angry2 at centre',
			'Chernii Спасибо!',
			'Только вот у него больше не было воды, но зато возник мерзкий план.',
			'show character Chernii disgust at centre with fadeIn',
			'Вместо воды у Аша было 4 сочных зайца.',
			'Перед ним высветилось уведомление.',
			'Text Изучена новая эмоция - отвращение.',
			'jump Scene13'
		],
		'Scene13': [ 
			'show scene home with fadeIn',
			'Вернувшись домой, он лег на пол рядом с Вечной, обнял и заснул.',
			'Стараясь не вспоминать прошедший день.',
			'show character Chernii normal at centre with fadeIn',
			'Через несколько часов, его разбудило уведомление “вас приглашают на свидание',
			'Chernii Зря.',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Сестра искала что-то в холодильнике. Достала лимонад "Тархун"',
			'hide character Vechna',
			'show character Chernii disgust at centre with fadeIn',
			'Chernii Убери это!',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Но сестра не смотрела в его сторону и не могла услышать.',
			'hide character Vechna',
			'show character Chernii disgust at centre with fadeIn',
			'Он отвернулся, к горлу подступала тошнота.',
			'Chernii Похоже, пить газировку я бросил.',
			'Вечна подошла к кроватям и поднялась наверх. Он хотел подойти.',
			'hide character Chernii',
			'show character Vechna whitenoise at centre with fadeIn',
			'Но не стал, в 6:00 она вновь выйдет в сеть, значит спать ей всего 4 часа.',
			'hide character Vechna',
			'show character Chernii surprised at centre with fadeIn',
			'Раздался звук уведомления.',
			'Вы должны посетить свидание.',
			'show character Chernii normal at centre',
			'Chernii Чувствую, у моего эксперимента мало шансов. Но они есть, а у свиданий их еще меньше.',
			'Он смотрел на сестру.',
			'Chernii Правила станции против меня. Но тот кто создал ее ИИ, скорее всего знал – будут и заложники ситуации',
			'Chernii Правильный вывод сделали на Биосфера 2: человек - самое непредсказуемое звено в технологиях и законах.',
			'Chernii Я бы следовал правилам, если бы не знал реальный источник проблемы. А это Вечна. в прямом смысле, подарившая мне грусть',
			'Chernii И во встрече с ней – мне отказано.',
			'jump Scene14'
		],
		'Scene14': [ 
			'show scene audience with fadeIn',
			'',
			'show character Chernii normal at centre with fadeIn',
			'Войдя в аудиторию, парня снова накрыло чувство, что кроме него здесь кто-то есть. Он пошел вдоль рядов.',
			'Chernii Есть тут кто?',
			'show character Chernii surprised at centre',
			'В первых рядах лежал человек, подключенный к сети. Он вальяжно развалился на скамье с довольной ухмылкой на лице.',
			'show character Chernii normal at centre',
			'Она отлично подходила его костюму и галстуку с аистом. Аш представил эту улыбочку на лице бодрствующего парня.',
			'Chernii Нашел что надеть. И кого-то мне смутно напоминаешь… А, все равно.',
			'Он ушел в дальний угол и вышел в сеть.',
			'jump Scene15'
		],
		'Scene15': [
			'show scene vr with fadeIn',
			'',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Если идти ва-банк, мне снова нужен этот M.Stork.',
			'Ему ответил неавторизованный пользователь.',
			'Аш услышал смех.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'Привет! Я знал, что мы отличная команда!',
			'hide character M',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Согласен, не плохая.',
			'Chernii Но не жди, что я пойду на поводу – не стал пить зайцев в тот раз, не опущусь и в этот.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Я из-за тебя конкретно не досыпаю. Как на хакатоне!',
			'M Если честно, сегодня я сам себя превзошел.',
			'hide character M',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Раз так, сразу ограничение по времени - 3 часа. И я закрываю доступ к управлению телом.',
			'hide character Chernii',
			'show character M noise at centre with fadeIn',
			'M Хорошо. Стартуем?',
			'hide character M',
			'show character Chernii confused at centre with fadeIn',
			'Chernii Быстро ты согласился. Подозрительно.',
			'Перед Ашем снова высветилось приглашение на свидание.',
			'show character Chernii normal at centre',
			'Chernii А ладно, Только давай быстрее, у меня мало времени.!',
			'jump Scene16'
		],
		'Scene16': [
		'show scene home with fadeIn',
		'',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Эээ... У тебя совсем нет чувства меры?',
		'hide character Chernii',
		'show character M noise at centre with fadeIn',
		'M Зря ты не играл за проектировщика. Тогда бы знал.',
		'hide character M',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Что на этот раз придумала твоя больная голова?',
		'hide character Chernii',
		'show character M noise at centre with fadeIn',
		'M Больная голова такое не придумает!',
		'hide character M',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Цель?',
		'hide character Chernii',
		'show character M noise at centre with fadeIn',
		'M Просто ждать. Неделю.',
		'hide character M',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii О чем мы только что говорили?',
		'hide character Chernii',
		'show character M noise at centre with fadeIn',
		'M Сюрприз! Есть инструменты искажения времени.',
		'hide character M',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii А я же чувствовал!',
		'hide character Chernii',
		'show character M noise at centre with fadeIn',
		'M Пока, еще увидимся!',
		'hide character M',
		'',
		'show character Chernii normal at centre with fadeIn',
		'Послышалось шуршание одеяла, кто-то зевнул.',
		'Парень обернулся к кровати, сердце замерло.',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Доброе утречко! Сделаешь чай?',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Привет! Конечно сделаю!',
		'Chernii * Мысли * Тоже мне, страшилка! Знал бы он, как я этого хотел.',
		'Chernii * Мысли * Интересно, это снизит показатели стресса?',
		'hide character Chernii',
		'show character Vechna smile at centre with fadeIn',
		'Vechna Аш!',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Ммм?',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Я решила, что не хочу тратить время на вещи, находящиеся дальше Луны.',
		'hide character Vechna',
		'show character Chernii surprised at centre with fadeIn',
		'Chernii Совсем?',
		'show character Chernii confused at centre',
		'Chernii * Мысли * Не похоже на Вечну. Плохая симуляция вышла, дружище.',
		'hide character Chernii',
		'show character Vechna smile2 at centre with fadeIn',
		'Vechna Ага, семья же - главное.',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii * Мысли * А может не такая уж и плохая.',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Чай уже готов?',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Еще нет.',
		'Он направился к кухонной стойке и открыл шкаф.',
		'Chernii Чем бы ты хотела заняться?',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Чем хочешь ты, главное вместе.',
		'hide character Vechna',
		'show character Chernii confused at centre with fadeIn',
		'Chernii Это очень мило, давно я от тебя такого не слышал.',
		'Chernii * Мысли * Совсем ничего не слышал.',
		'show character Chernii normal at centre',
		'Он насыпал чайный порошок в кружку и добавил сироп. Поставил в бокс.',
		'Аппарат наполнил сосуд водой и зафиксировал его. Включилась магнитная мешалка.',
		'Chernii На Лунном Озере классно. Меня всегда завораживала самоподдерживающаяся масса наноботов. Пусть это и "свалка", но они как клетки.',
		'Chernii Убивают дефектных, собирают из расщепленных веществ новых. Круто же!',
		'Он поставил перед сестрой чашку и пошел к двери. Та не открывалась.',
		'Chernii Попробовать стоило.',
		'hide character Chernii',
		'show character Vechna smile2 at centre with fadeIn',
		'Vechna Тогда поговорим!',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Ты мне нравишься такой!',
		'Chernii * Мысли * Интересно, мой стресс уже упал до нуля?',
		'Chernii Рассказать про мои импланты? Я сильно продвинулся!',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Если ты хочешь… Но, если честно, мне он не нравится.',
		'hide character Vechna',
		'show character Chernii surprised at centre with fadeIn',
		'Chernii Почему?',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Ты тратишь на него так много времени в сети!',
		'hide character Vechna',
		'show character Chernii surprised at centre with fadeIn',
		'Chernii Но мы покоряем космос. Когда-нибудь появятся настолько далекие колонии, что люди превратятся в разные виды.',
		'Chernii Даже живя на Земле, мы имеем разные культурные коды. Разные языки. Нам нужно что-то универсальное.',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Ты даже не доживешь до этого!',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Если умирать придется, то можно и в сеть скопироваться – пополнить ряды сетевиков.',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Я не стану.',
		'hide character Vechna',
		'show character Chernii surprised at centre with fadeIn',
		'Chernii Серьезно? Я бы не пережил твою смерть.',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Значит я умру, а ты будешь готовить чай моей копии? Нет уж.',
		'hide character Vechna',
		'show character Chernii confused at centre with fadeIn',
		'Chernii Это… Эгоистично… Если технологии дают хоть какой-то шанс прожить две жизни…',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Тебе придется смириться.',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Я бы так с тобой не поступил.',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Не уверена, что смогла бы наладить контакт с твоей версией 2.',
		'Vechna И для чего эти разговоры? Еще годик - и мы будем на Земле! Там можно вообще отключиться от сети. Уедем на ферму?',
		'hide character Vechna',
		'show character Chernii confused at centre with fadeIn',
		'Chernii Эм, а как же мой проект?',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Разве он важнее меня?',
		'hide character Vechna',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii Ты не поняла меня.',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Ну конечно! Я готова проводить с тобой все свое время, а ты готов отказаться от этого, ради каких-то фантазий!',
		'hide character Vechna',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii * Мысли * Это будет сложная неделя.',
		'hide character Chernii',
		'Вечна бредила о Земле, заканчивая все разговоры о его и своем деле жизни истерикой.',
		'Ему казалось, она доводит все до абсурда.',
		'Один раз сказал, что попробует поработать. Сидеть в 4х стенах - пытка.',
		'Но она намеренно отвлекала, рассказывая, почему все это - ерунда.',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii Я не могу целый день фантазировать о Земле. Пока мы на Луне и, фактически, сформировались здесь как личности.',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Вот и пора это заканчивать!',
		'hide character Vechna',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii Я просто не могу бросить проект. Я... Я...',
		'Он вспомнил последний разговор с настоящей сестрой.',
		'Chernii Возможно, я перегнул палку со своими требованиями.',
		'show character Chernii normal at centre',
		'Chernii И моя проблема, не только в Вечне...',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Не знаю о чем ты, но мне твой настрой нравится.',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Хочешь поговорить о тебе?',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna О чем мне рассказывать? Моя жизнь – это ты. А о себе ты знаешь больше, чем я.',
		'hide character Vechna',
		'show character Chernii normal at centre with fadeIn',
		'Chernii Ты не хочешь слушать про настоящего меня и мои проблемы.',
		'Chernii * Мысли * Вот черт, кого-то это мне напоминает...',
		'hide character Chernii',
		'Дни тянулись долго, проектировщик не отвечал.',
		'Вечна часами говорила обо всем на свете, но не о том, что для него важно и интересно.', 
		'Любые попытки поговорить на интересные ему темы пресекались.',
		'К концу третьего дня, игрок испытывал непрекращающееся раздражение.',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii Ты не можешь общаться со мной, словно я другой человек. Мне это не интересно, я не хочу отключаться от сети!',
		'Chernii Без нее мы в дополненной реальности даже номера домов не увидим, не прочтем состав еды на пачке!',
		'Chernii Как ты можешь забывать, что все, что можно напечатать или написать, все дорожные знаки – все это доступно через чип, в дополненной или виртуальной реальности.',
		'Chernii Что ты вообще несешь?',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Ты не хочешь меня понять!',
		'hide character Vechna',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii АААА! Я так больше не могу. Просто, давай молчать, не говори со мной. Умоляю.',
		'Он ожидал, что девушка зальется слезами.',
		'hide character Chernii',
		'show character Vechna angry at centre with fadeIn',
		'Но вместо этого, она взяла с полки его любимую статуэтку и бросила о стену.',
		'Осколки отлетели с такой силой, что пролетели практически до противоположной стены.',
		'show character Vechna thinking at centre',
		'После этого, девушка обиженно села на кровать.',
		'hide character Vechna',
		'show character Chernii annoyed at centre with fadeIn',
		'Сдержать ругань парню помогла мысль, что это не настоящая статуэтка.',
		'show character Chernii normal at centre',
		'Chernii Ау!',
		'Но боль от отскочивших осколков была настоящая.',
		'Чип в голове подавал на мозг электрические импульсы. И делал это быстрее, чем настоящие рецепторы.',
		'show character Chernii annoyed at centre',
		'Chernii Адекватная Вечна хотя бы убрала это за собой. Дашь клей для ран?',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Нет. Ты же не хочешь обо мне заботиться, тебе важнее мечты!',
		'Vechna Амбиции, которые можно реализовать дальше Луны, там, где меня нет.',
		'hide character Vechna',
		'show character Chernii annoyed at centre with fadeIn',
		'Закипая от гнева. Он сам достал клей, включил робота, чтобы тот убрал осколки.',
		'show character Chernii normal at centre',
		'Не говоря ни слова, лег на кровать и постарался уснуть. Ничего не выходило, Вечна снова начала причитать.',
		'',
		'Chernii Ты заметила, что мы не спим уже три дня?',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Я не чувствую себя усталой. Почему бы нам не решить наши проблемы?',
		'hide character Vechna',
		'show character Chernii disgust at centre with fadeIn',
		'hide character Chernii',
		'show character Chernii angry at centre',
		'Chernii О космос! Лучше убей меня!',
		'hide character Chernii',
		'',
		'show character Chernii sad at centre with fadeIn',
		'Через день Аш уже уговаривал Макса выпустить его. В тот день, пришло уведомление',
		'Открыта новая эмоция – грусть',
		'hide character Chernii',
		'Находиться в комнате с эгоистичным, давящим на жалость и игнорирующим его слова существом стало невозможно.',
		'За один день в доме закончилась посуда, и были убиты все растения и насекомые в фудрариуме.',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Раз ты не хочешь со мной готовить - мы не будем есть.',
		'Сказала она - и включила в фудрариумах температуру 100 градусов.',
		'hide character Vechna',
		'Она не давала ему спать, совсем. Но усталость была самая настоящая. По крайней мере, так ему казалось.',
		'В комнате постоянно стоял крик.',
		'show character Chernii angry2 at centre with fadeIn',
		'Chernii Если честно, я очень надеюсь, что умру сегодня от голода, или чего угодно еще! Лишь бы не видеть тебя!',
		'Chernii Видит сеть, я не того свидания с тобой добивался!',
		'Chernii * Мысли * Как закончить игру? Я больше не могу.',
		'Теперь парень не выходил из состояния постоянной злости. Но злился он и на себя - стало очевидно, как он выглядит для сестры.',
		'Chernii * Мысли * Просто изолятор для психически больных, а не симуляция.',
		'hide character Chernii',
		'',
		'Прошел еще день.',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii * Мысли * Перерезать горло? Распотрошить технику и отравиться? Или башкой об угол?',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Брат...',
		'hide character Vechna',
		'show character Chernii disgust at centre with fadeIn',
		'Он стал ненавидеть это слово.',
		'hide character Chernii',
		'show character Vechna normal at centre with fadeIn',
		'Vechna Мне скучно.',
		'hide character Vechna',
		'show character Chernii annoyed at centre with fadeIn',
		'Chernii * Мысли * Башкой об угол, значит...',
		'Он уже не сдерживал свой гнев.',
		'show character Chernii angry at centre',
		'Chernii Займи себя чем-нибудь еще. Правда, у меня есть дела поважнее. Мне нужно покинуть это место.',
		'hide character Chernii',
		'show character Vechna angry at centre with fadeIn',
		'Vechna Ты меня бросаешь?',
		'hide character Vechna',
		'show character Chernii angry2 at centre with fadeIn',
		'Chernii Да! Я тебя бросаю! Только не контактируй со мной.',
		'Больше всего его бесило, что она не грустит, а злиться на него.',
		'Chernii До себя совсем не доходит, что причина наших проблем, может быть в твоем отношении?',
		'hide character Chernii',
		'show character Vechna angry at centre with fadeIn',
		'Vechna Как тебе хватает совести?',
		'hide character Vechna',
		'show character Chernii disgust at centre with fadeIn',
		'Chernii Но Ашу хватало. В первую очередь, он говорил сам с собой.',
		'Chernii Неужели я настолько предвзят?',
		'show character Chernii normal at centre',
		'Он постарался лечь в кровать, игнорируя девушку, ломающую мебель для привлечения внимания.',
		'Но она встала рядом и трясла его за плечо.',
		'show character Chernii angry at centre',
		'Chernii Хватит! Уйди!',
		'Chernii Он с силой оттолкнул ее от себя.',
		'show character Chernii angry2 at centre',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Куда я уйду?',
		'hide character Vechna',
		'show character Chernii angry at centre with fadeIn',
		'Chernii * Мысли * Пора заканчивать.',
		'Он поднял робота для уборки и открыл контейнер. Осколков для посуды там не было.',
		'Chernii Плевать!',
		'Ударил робота об пол, достал аккумулятор и вскрыл его, высыпав на руку содержимое.',
		'Горло, рот и руку обожгла кислота. Внутренности плавились. Вокруг причитала Вечна.',
		'hide character Chernii',
		'show character Vechna thinking at centre with fadeIn',
		'Vechna Какой ты эгоист!',
		'hide character Vechna',
		'show character Chernii angry2 at centre with fadeIn',
		'Парень уже начал терять сознание... Но, проектировщик изменил свойства кислоты. Она больше не разъедала внутренности.',
		'show character Chernii veryangry at centre with fadeIn',
		'Chernii Черт! Тогда бы и внутренности починил.',
		'Он загибался от боли.',
		'Chernii Зря закрыл доступ к управлению телом... Ничего он не залечит. Еще 2 дня.',
		'hide character Chernii',
		'show character Vechna angry at centre with fadeIn',
		'Девушка предъявляла все больше претензий, не давая спать.',
		'hide character Vechna',
		'show character Chernii veryangry at centre',
		'Аш злился, что она испортила еду.',
		'Chernii Не подходи ко мне, или я сделаю тебе больно. Сиди и молчи.',
		'show character Chernii normal at centre',
		'Через несколько часов Аш лежал на кровати и спал. Рядом с кухонной стойкой лежала девушка. Тихо и мирно.',
		'Раздался звук сообщения.',
		'Chernii Еще ведь целые сутки? Мне что, нужно было ее убить по правилам игры?',
		'Ему никто не ответил.',
		'Chernii * Мысли * Убить бы и проектировщика...',
		'Высветилось сообщение: вы отключены от сети.',
		'jump Scene17'
		],
		'Scene17': [
			'show scene audience with fadeIn',
			'Голова раскалывалась, он не решался подняться со скамьи и пойти домой. Кошмар еще не отпустил.',
			'show character Chernii fear at centre with fadeIn',
			'Chernii * Мысли * Отключен?',
			'Он попробовал войти в сеть. Но ничего не изменилось.',
			'Chernii Там же все... Нет доступа к коду моих имплантов, я не смогу ими заниматься! Я не смогу их обучить! А Вечна? Настоящая, адекватная Вечна?',
			'Он сел на скамейку, не поднимая глаза на мир вокруг. Он не хотел смотреть на единственный, доступный ему мир. Сердце колотилось.',
			'show character Chernii sad at centre',
			'О космос! Эта жизнь злее, чем ты.',
			'Он встал на ноги и начал ходить туда обратно. Ладони в карманах толстовки вспотели.',
			'Chernii Мне остается только добиться этого "лечебного" свидания в реальности.',
			'Паника немного отступала.',
			'show character Chernii normal at centre',
			'Chernii Ладно. Дообучить базовые эмоции я могу и на станции.',
			'Chernii Но у меня даже нет данных к библиотеке того, какие эмоции с какой вероятностью отображаются!',
			'show character Chernii fear at centre',
			'Chernii Или по каким параметрам искусственный интеллект ушей отличает одну эмоцию от другой. Там может быть куча ошибок!',
			'Chernii Как мне теперь понять, какие эмоции ИИ уже научился определять?',
			'show character Chernii confused at centre',
			'Chernii Неужели, придется по-тупому смотреть в зеркало, и так определять, во время какой эмоции отображаются помехи, а во время какой четкое изображение на дисплеях?',
			'А если все пойдет не так, я не смогу изменить ИИ имплантов?',
			'show character Chernii normal at centre',
			'Нужно попробовать. Осталась неделя, чтоб связаться с Вечной.',
			'Он почувствовал движение воздуха.',
			'Chernii Здесь же был какой-то парень, когда я уходил в сеть?',
			'Он еще собирался с мыслями, что это такое было.',
			'Опять почувствовалось движение воздуха, и Аш повернул лицо в его сторону.',
			'show character Chernii fear at centre',
			'Chernii Только не ты.',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Сожалею, но вы проигнорировали условия Центра Помощи. В связи с ситуацией, вас вынуждены заблокировать сегодня в полночь.',
			'hide character Station_AI',
			'show character Chernii confused at centre with fadeIn',
			'Chernii Стой! У меня ведь еще неделя!',
			'hide character Chernii',
			'Доброжелательным голосом робот повторил.',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI Вы не посетили ни одного свидания. А ваш уровень стресса увеличивается экспоненциально.',
			'hide character Station_AI',
			'show character Chernii fear at centre with fadeIn',
			'Колени Аша подкосились, он сел на скамью. Голова налилась тяжестью',
			'hide character Chernii',
			'show character Station_AI normal at centre with fadeIn',
			'Station_AI После блокировки просьба явиться в Центр Помощи.',
			'hide character Station_AI',
			'Мобильная камера ИИ станции выплыла из помещения, оставляя после себя движение воздуха и отчаяние парня.',
			'show character Chernii fear at centre with fadeIn',
			'Chernii Значит все? Неужели все может измениться так резко?',
			'Chernii Хотя, какое резко... Все давно катилось в...',
			'На его плечо опустилась рука.',
			'show character Chernii surprised at centre',
			'Аш подскочил и развернулся. Перед ним стоял парень, которого он видел в аудитории раньше.',
			'hide character Chernii',
			'show character Max normal at centre with fadeIn',
			'Max Спасибо за игру!',
			'Max Но, честно, реальность у тебя похлеще любой из них.',
			'hide character Max',
			'show character Chernii disgust at centre with fadeIn',
			'Chernii А я думал, где же тебя видел...',
			'hide character Chernii',
			'show character Max normal at centre with fadeIn',
			'Max Вообще, ты меня видел на лекциях в виаре. У нас один универ.',
			'hide character Max',
			'show character Chernii sad at centre with fadeIn',
			'Chernii Теперь, парень, мне эта информация точно ни к чему.',
			'hide character Chernii',
			'show character Max normal at centre with fadeIn',
			'Max Максим.',
			'hide character Max',
			'show character Chernii sad at centre with fadeIn',
			'Chernii На игре у меня было к тебе столько вопросов, но теперь, если честно – плевать.',
			'hide character Chernii',
			'show character Max normal at centre with fadeIn',
			'Max Учитывая твою ситуацию, я бы не брезговал общением.',
			'Max Как неплохой психолог, понимаю, тебе здесь должно быть тошно.',
			'Max Уйдем отсюда?',
			'jump Scene18'
		],
		'Scene18': [
			'show scene lake with fadeIn',
			'',
			'show character Chernii sad at centre with fadeIn',
			'Chernii За твои игры тебя бы растворить в этом потоке наноботов, как мусор, который в него бросают.',
			'hide character Chernii',
			'show character Max fight at centre with fadeIn',
			'Max Попробуй, конечно.',
			'Max Но в игру ты сам пришел. И правила знал до этого.',
			'hide character Max',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Как ты сделал эту комнату с сестрой, что ты про меня знаешь и откуда?',
			'hide character Chernii',
			'show character Max fight at centre with fadeIn',
			'Max Я смотрю, тот факт, что ты всегда играл за жертву, сыграл с тобой злую шутку.',
			'hide character Max',
			'show character Chernii surprised at centre with fadeIn',
			'Chernii ?',
			'hide character Chernii',
			'show character Max fight at centre with fadeIn',
			'Max Ты первые игры открывал полный доступ для проектировщика.',
			'Max А мой стиль – использовать данные по полной. Я банально взял твою галерею, не так просто придумать для тебя ужас.',
			'Max На случай если ты вернешься, сохранил данные и...',
			'Max Недавно посмотрел Черное Зеркало. Серия белое рождество. Типа культовая, сам знаешь почему.',
			'Max Я не знал о твоих терках с сестрой, но решил закрыть тебя во временной петле, без возможности выйти – как раз как в серии.',
			'hide character Max',
			'show character Chernii angry2 at centre with fadeIn',
			'Chernii Вот я идиот!',
			'hide character Chernii',
			'show character Max normal at centre with fadeIn',
			'Max Да нет, я это я хитрый.',
			'hide character Max',
			'show character Chernii normal at centre with fadeIn',
			'Chernii И скромный.',
			'hide character Chernii',
			'show character Max fight at centre with fadeIn',
			'Max Если перегнул, то все равно не извиняюсь. Нужно было читать правила.',
			'Max Удивляюсь, как мало данных используют другое проектировщики.',
			'Max Чувство, что там народ только дизайном локаций и персов занимается.',
			'hide character Max',
			'show character Chernii sad at centre with fadeIn',
			'Chernii Ты еще как перегнул, но блин. Мне пришла в голову важная мысль.',
			'Он остановился, обдумывая, стоит ли рассказывать явно не слишком адекватному парню личные вещи.',
			'Но решил, что это, возможно, последний человек, с которым он может поговорить.',
			'Chernii Возможно, я реально задушил свою сестру "заботой", о которой меня никто не просил. Конечно, не так как она меня в игре, но...',
			'hide character Chernii',
			'show character Max normal at centre with fadeIn',
			'Max Я старался довести все до абсурда, и честно, допиливал все в реальном времени...',
			'hide character Max',
			'show character Chernii annoyed at centre with fadeIn',
			'Chernii Я не о тебе. Ты приговоренному к смерти не дашь слово вставить...',
			'hide character Chernii',
			'show character Max normal at centre with fadeIn',
			'Max Какая ирония, мы познаем себя настоящих в виртуальной среде.',
			'hide character Max',
			'show character Chernii annoyed at centre with fadeIn',
			'Chernii "Психолог", ты совсем не слышал, что я сказал?',
			'hide character Chernii',
			'show character Max normal at centre with fadeIn',
			'Max ...',
			'hide character Max',
			'show character Chernii annoyed at centre with fadeIn',
			'Chernii Плевать. Заблоченных не шлют на Землю, даже если они выполняют все требования. Их шлют в дальний космос.',
			'hide character Chernii',
			'show character Max normal at centre with fadeIn',
			'Max Удобная система "добровольцев", нет бы пиаром пионеров занимались.',
			'hide character Max',
			'show character Chernii annoyed at centre with fadeIn',
			'Chernii Если честно, мне уже плевать. Я давил на близкого человека, а она всего то хочет - открывать то, что дальше Луны.',
			'hide character Chernii',
			'show character Max normal at centre with fadeIn',
			'Max опять положил руку на плечо парня.',
			'Max Ты теперь тоже будешь изучать то, что дальше нее.',
			'hide character Max',
			'show character Chernii veryangry at centre with fadeIn',
			'Chernii Хватит меня трогать!',
			'Он направился к выходу.',
			'show character Chernii veryangry at centre with fadeIn',
			'Chernii Мне нужно домой.',
			'hide character Chernii',
			'show character Max normal at centre with fadeIn',
			'Max Заходи поиграть, если что.',
			'hide character Max',
			'show character Chernii anngry2 at centre with fadeIn',
			'Chernii Смешно. И удали мои данные!',
			'hide character Chernii',
			'show character Max fight at centre with fadeIn',
			'Максим в ответ улыбнулся, но Аш уже скрылся за поворотом.',
			'jump Scene19'
		],
		'Scene19': [
			'show scene home with fadeIn',
			'',
			'show character Vechna whitenoise at centre with fadeIn',
			'Девушка бодрствовала. Она сидела за столом, перед ней стояла одна тарелка.',
			'hide character Vechna',
			'show character Chernii sad at centre with fadeIn',
			'У него скрутило желудок, но готовить сил не было.',
			'Chernii Я просто побуду с тобой, не знаю, зачем. Для меня ситуация с тобой не изменится.',
			'Chernii А тебе потом придется привыкнуть.',
			'Он сел на пол и облокотился на ее кровать.',
			'Chernii Я даже не могу узнать время до полуночи...',
			'Chernii Все-таки, я привык к сети.',
			'',
			'Он закрыл глаза. В жилых блоках, расположенных в лавовых туннелях под поверхность Луны, ты быстро дезориентировался во времени, если нет часов.',
			'Он не знал, сколько проспал. Его разбудило прикосновение руки.',
			'Chernii Макс, отвали!',
			'Chernii * Мысли * Какой Макс?!',
			'Он открыл глаза. Рядом с ним на полу сидела сестра.',
			'hide character Chernii',
			'show character Vechna normal at centre with fadeIn',
			'Vechna Ты почему так рано? И такой убитый?',
			'hide character Vechna',
			'show character Chernii annoyed at centre with fadeIn',
			'Chernii Ты? Ты так просто спрашиваешь?',
			'По лицу девушки было видно, что она понимала вопрос. Но старалась не подавать виду.',
			'hide character Chernii',
			'show character Vechna normal at centre with fadeIn',
			'Vechna Я думала, ты доделал свои заячьи ушки... И вот...Ты же сам сказал, нужно 3 месяца... А не как мне – года...',
			'hide character Vechna',
			'show character Chernii veryangry at centre with fadeIn',
			'По его телу разлился огонь.',
			'Chernii Доделал? Я только ради тебя их и делал! Думал, ты со мной никогда не заговоришь!',
			'hide character Chernii',
			'show character Vechna normal at centre with fadeIn',
			'Vechna Ты же хотел, чтоб я помогла. В итоге, я сама себе готовила и не отвлекала тебя. Но, да... Стоило поговорить...',
			'hide character Vechna',
			'show character Chernii sad at centre with fadeIn',
			'Chernii Я тоже должен извиниться, при странных обстоятельствах понял, каково это - когда тебя тормозят в достижении цели. Я такое пережил...',
			'Он вспомнил последнюю игру Максима. И сразу же постарался забыть.',
			'hide character Chernii',
			'show character Vechna smile at centre with fadeIn',
			'Ого! Мне это очень приятно! Я тоже дура, зато с готовой симуляцией!',
			'hide character Vechna',
			'show character Chernii happy at centre with fadeIn',
			'Chernii Я скучал.',
			'hide character Chernii',
			'show character Vechna normal at centre with fadeIn',
			'Vechna Я на самом деле тоже, тяжело столько молчать.',
			'show character Vechna smile at centre with fadeIn',
			'Vechna Расскажи, ты ведь закончил проект?',
			'hide character Vechna',
			'show character Chernii normal at centre with fadeIn',
			'Chernii Уши уже не важны – меня заблокировали в сети. Я не смогу продолжить нормально работать без доступа к коду.',
			'hide character Chernii',
			'show character Vechna angry at centre with fadeIn',
			'Vechna Как заблокировали? Они нарушают права человека!',
			'Vechna Я могу переписать тебе код на физический носитель! Не знаю, как с ним работать, но помогу!',
			'hide character Vechna',
			'show character Chernii happy2 at centre with fadeIn',
			'Chernii Не сможешь. Я игнорировал требования ИИ станции, который обязал посещать свидания для снижения стресса. Короче, меня заблочат в полночь. По полной.',
			'hide character Chernii',
			'show character Vechna thinking at centre with fadeIn',
			'Vechna Что с ними можно сделать?',
			'hide character Vechna',
			'show character Chernii happy at centre with fadeIn',
			'Chernii Не знаю. Я просто рад, что смог встретиться с тобой.',
			'hide character Chernii',
			'show character Vechna thinking at centre with fadeIn',
			'Vechna Мило, но я это так не оставлю. Я хотела показать тебе свою работу!',
			'hide character Vechna',
			'show character Chernii happy at centre with fadeIn',
			'Chernii Говорят, я слишком нервный и неустойчивый, а для станции это значит - опасный.',
			'Аш услышал звук уведомления.',
			'Chernii Подожди…',
			'Он с замершим сердцем прочитал сообщение.',
			'Сообщение: Уровень стресса значительно снижен. Вам восстановлен доступ в сеть. Явитесь в Центр Помощи в течении 24 часов.',
			'Блокировка в полночь приостановлена. Вы должны закончить программу реабилитации и посетить назначенные свидания.',
			'Он повернулся к сестре.',
			'Chernii Что ты мне хотела показать?',
			'hide character Chernii',
			'show character Vechna smile at centre with fadeIn',
			'Vechna Все ок?',
			'hide character Vechna',
			'show character Chernii happy2 at centre with fadeIn',
			'Chernii Да.',
			'hide character Chernii',
			'Они вошли в сеть',
			'show scene planet with fadeIn',
			'Chernii Настоящее свидание - это не то, как вы близко, это то, насколько вы стали ближе.'




			






























		
	


			


			
			


	



		

			

			











			






















			






















		






















		],















		







})